---
- name: Create Admin service account
  oc_serviceaccount:
    name: kuryr-controller
    namespace: default
  register: saout

- name: Create a role for the Kuryr controller
  oc_clusterrole:
    name: kuryrctl
    state: present
    rules:
      - apiGroups:
        - ""
        attributeRestrictions: null
        verbs:
          - get
          - list
          - watch
        resources:
          - daemonsets
          - deployments
          - deploymentconfigs
          - endpoints
          - ingress
          - nodes
          - namespaces
          - pods
          - policies
          - projects
          - routes
          - services
      - apiGroups:
        - ""
        attributeRestrictions: null
        verbs:
          - update
          - patch
        resources:
          - endpoints
          - ingress
          - pods
          - namespaces
          - nodes
          - services
          - services/status
          - routes

- name: Fetch the created Kuryr controller cluster role
  oc_clusterrole:
    name: kuryrctl
    state: list
  register: crout

- name: Assign role to Kuryr service account
  oc_adm_policy_user:
    user: "{{ saout.results.results.0.metadata.name }}"
    resource_kind: cluster-role
    resource_name: "{{ crout.results.results.metadata.name }}"
    state: present

- name: Generate the Kuryr controller client config
  command: >
    {{ openshift.common.client_binary }} adm create-api-client-config
      --certificate-authority={{ openshift_master_ca_cert }}
      --client-dir={{ kuryr_config_dir }}
      --master={{ openshift.master.api_url }}
      --public-master={{ openshift.master.api_url }}
      --signer-cert={{ openshift_master_ca_cert }}
      --signer-key={{ openshift_master_ca_key }}
      --signer-serial={{ openshift_master_ca_serial }}
      --basename='controller'
      --user={{ saout.results.results.0.metadata.name }}

- name: Make kuryr own the certs
  file:
    path: "{{ item }}"
    owner: kuryr
    group: kuryr
    mode: 0660
  with_items:
    - "{{ kuryr_config_dir }}/ca.crt"
    - "{{ kuryr_config_dir }}/controller.crt"
    - "{{ kuryr_config_dir }}/controller.key"
    - "{{ kuryr_config_dir }}/controller.kubeconfig"
